package com.aiteacher.service;

import com.aiteacher.dto.LessonPlanResponse;
import com.aiteacher.dto.StudentProfileRequest;

/**
 * Phase 3 contract for AI-powered lesson generation. Implementations call a
 * real AI provider behind this interface, so the provider can be swapped
 * without touching controllers or the frontend.
 */
public interface AIService {

	/**
	 * Generates a structured, personalized lesson plan from the student's actual
	 * profile input. The returned plan echoes the submitted profile values and
	 * carries lesson content generated by the AI provider in the student's
	 * selected language, adapted to their education level, teaching style and
	 * learning objective.
	 *
	 * @param profile the validated student profile (never replaced by defaults)
	 * @return the AI-generated lesson plan
	 * @throws com.aiteacher.ai.AiException when the AI is unconfigured, the call
	 *         fails upstream, or the provider response cannot be validated
	 */
	LessonPlanResponse generateLesson(StudentProfileRequest profile);
}
