package com.aiteacher.dto;

import java.util.List;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Phase 6 response containing a dynamically generated question.
 * The question is produced by the AI based on actual lesson content —
 * never from a hardcoded bank.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class QuestionResponse {

    /** The question type: MCQ or SHORT_ANSWER. */
    private String type;

    /** The question text generated by the AI. */
    private String question;

    /** For MCQ: the list of answer options (always 4). */
    private List<String> options;

    /** For MCQ: the zero-based index of the correct option. */
    private Integer correctOptionIndex;

    /** For SHORT_ANSWER: a model answer or key concept the AI expects. */
    private String expectedConcept;

    /** Unique identifier for this question (used to track the answer). */
    private String questionId;
}
